# Generated by Django 3.2 on 2021-04-20 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_contact_no', models.CharField(max_length=10)),
                ('patient_email', models.EmailField(max_length=254, null=True)),
                ('patient_age', models.CharField(max_length=3)),
                ('patient_blood_group', models.CharField(choices=[('AB-', 'AB-'), ('AB', 'AB'), ('AB+', 'AB+'), ('A-', 'A-'), ('A', 'A'), ('A+', 'A+'), ('B-', 'B-'), ('B', 'B'), ('B+', 'B+'), ('O-', 'O-'), ('O', 'O'), ('O+', 'O+')], max_length=3)),
                ('patient_sp02_level', models.CharField(max_length=2)),
                ('patient_requirements', models.CharField(choices=[('B', 'Bed'), ('I', 'ICU'), ('O', 'Oxygen'), ('P', 'Plasma'), ('R', 'Remidisiver'), ('M', 'Other Medicines')], max_length=1)),
                ('alternate_contact', models.CharField(blank=True, max_length=100)),
                ('alternate_contact_no', models.CharField(blank=True, max_length=10)),
                ('location_city', models.CharField(help_text='The city where the patient needs help', max_length=30)),
                ('location_hospital', models.CharField(blank=True, help_text='If the patient is aleady in a hospital', max_length=100)),
                ('status', models.CharField(choices=[('O', 'New'), ('C', 'Closed')], default='O', max_length=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('additional_text', models.TextField(blank=True, help_text='Any additional details you may want to give')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
