# Generated by Django 3.2 on 2021-04-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Bed'), ('I', 'ICU'), ('O', 'Oxygen'), ('P', 'Plasma'), ('R', 'Remidisiver'), ('M', 'Other Medicines')], max_length=1)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('verified', models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified')], default='U', max_length=1)),
                ('last_verified', models.DateTimeField(auto_now=True)),
                ('additional_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-last_verified'],
            },
        ),
        migrations.AlterField(
            model_name='covidhelp',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='covidhelp',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1),
        ),
    ]
