# Generated by Django 3.2 on 2021-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210422_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='available',
            name='type',
            field=models.CharField(choices=[('B', 'Bed'), ('I', 'ICU'), ('O', 'Oxygen'), ('P', 'Plasma'), ('R', 'Remidisiver'), ('F', 'Fabiflu'), ('T', 'Tiffin'), ('M', 'Other Medicines')], max_length=1),
        ),
        migrations.AlterField(
            model_name='available',
            name='verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('F', 'Fake')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='covidhelp',
            name='patient_requirements',
            field=models.CharField(choices=[('B', 'Bed'), ('I', 'ICU'), ('O', 'Oxygen'), ('P', 'Plasma'), ('R', 'Remidisiver'), ('F', 'Fabiflu'), ('T', 'Tiffin'), ('M', 'Other Medicines')], max_length=1),
        ),
    ]
