# Generated by Django 3.2 on 2021-04-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210422_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='available',
            name='type',
            field=models.CharField(choices=[('B', 'Bed'), ('I', 'ICU'), ('O', 'Oxygen'), ('P', 'Plasma'), ('R', 'Remidisiver'), ('F', 'Fabiflu'), ('V', 'Favipiravir'), ('T', 'Tiffin'), ('M', 'Other Medicines')], max_length=1),
        ),
        migrations.AlterField(
            model_name='covidhelp',
            name='patient_blood_group',
            field=models.CharField(choices=[('AB-', 'AB-'), ('AB', 'AB'), ('AB+', 'AB+'), ('A-', 'A-'), ('A', 'A'), ('A+', 'A+'), ('B-', 'B-'), ('B', 'B'), ('B+', 'B+'), ('O-', 'O-'), ('O', 'O'), ('O+', 'O+'), ('ANY', 'ANY')], default='ANY', max_length=3),
        ),
        migrations.AlterField(
            model_name='covidhelp',
            name='patient_requirements',
            field=models.CharField(choices=[('B', 'Bed'), ('I', 'ICU'), ('O', 'Oxygen'), ('P', 'Plasma'), ('R', 'Remidisiver'), ('F', 'Fabiflu'), ('V', 'Favipiravir'), ('T', 'Tiffin'), ('M', 'Other Medicines')], max_length=1),
        ),
        migrations.AddField(
            model_name='available',
            name='type_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.requirements'),
        ),
        migrations.AddField(
            model_name='covidhelp',
            name='patient_requirements_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.requirements'),
        ),
    ]
