# Generated by Django 3.2 on 2021-04-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210423_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='type',
        ),
        migrations.RemoveField(
            model_name='covidhelp',
            name='patient_requirements',
        ),
    ]
