# Generated by Django 3.2 on 2021-04-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210423_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='available',
            old_name='type_link',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='covidhelp',
            old_name='patient_requirements_link',
            new_name='patient_requirements',
        ),
    ]
