# Generated by Django 3.2 on 2021-04-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210423_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='covidhelp',
            name='alternate_contact_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='covidhelp',
            name='patient_contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
