# Generated by Django 3.2 on 2021-04-27 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_available_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='available',
            options={'ordering': ['type', '-last_verified']},
        ),
        migrations.AlterModelOptions(
            name='covidhelp',
            options={'ordering': ['patient_requirements', '-date']},
        ),
        migrations.AlterModelOptions(
            name='requirements',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='link',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
