# Generated by Django 3.2 on 2021-05-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210427_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
